In [3]:
import numpy as np

# Soal 1

In [32]:
# np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

 ## Output

In [36]:
# arr = np.arange(0,10).reshape(2,5)
# arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [4]:
# arr1 = np.arange(10)
# np.array([list(arr1[:5]),list(arr1[5:])])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [8]:
# Reshape merubah struktur dari array numpy mjd (row, column) yg diinginkan.
# jika kita menulis -1 berarti numpy array akan secara otomatis menyesuaikan jumlah row / column nya
# np.arange(27).reshape(-1,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26]])

# Soal 2

In [10]:
# arr = np.arange(4,13).reshape(3,3)
# arr

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [83]:
# list = np.array([[arr[0][1],arr[0][0],arr[0][2]],
#                 [arr[1][1],arr[1][0],arr[1][2]],
#                 [arr[2][1],arr[2][0],arr[2][2]]])
# list

array([[ 5,  4,  6],
       [ 8,  7,  9],
       [11, 10, 12]])

In [12]:
# Indexing menggunakan [row, column] bisa mjd berlipat jika kita memasukan index
# yg sama di dalam list row/ column yg diinginkan
# arr[:,[1,0,0,2]]

array([[ 5,  4,  4,  6],
       [ 8,  7,  7,  9],
       [11, 10, 10, 12]])

# Soal 3

In [13]:
# arr = np.arange(9).reshape(3,3)
# arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## Output

In [79]:
# list = np.array([arr[2],arr[1],arr[0]])
# list

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [19]:
# sama spt indexing pd saat di list, bisa menggunakan ::-1 utk melakukan
# reverse balik di tingkat row maupun column
# arr[:,::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

# Soal 4

In [89]:
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

arr = np.array([arr1, arr2, arr3])
arr

array([array([0, 1, 2]), array([3, 4, 5, 6]), array([7, 8, 9])],
      dtype=object)

In [91]:
array1 = np.array([arr[0][0], arr[0][1], arr[0][2], arr[1][0], 
                   arr[1][1], arr[1][2], arr[1][3], 
                   arr[2][0], arr[2][1], arr[2][2]])
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
k = []
for i in arr :
    for j in i :
        k.append(j)
np.array(k)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [21]:
np.array([j for i in arr for j in i])

array([0, 1, 2, 3, 4, 5, 6, 7, 8])